apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: finite-deployment
  name: finite-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finite-deployment
  strategy: {}
  template:
    metadata:
      labels:
        app: finite-deployment
    spec:
      restartPolicy: Always
      containers:
      - image: busybox:1.36
        name: busybox
        command:
          - sh
          - -c
          - |
            echo "started"
            sleep 5
            echo "finished"
        resources: {}
status: {}
