apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-09-02T06:42:03Z"
  labels:
    app: inference
  name: inference-service
  namespace: default
  resourceVersion: "53909"
  uid: ef983e60-1892-4626-8afe-7ce2ebbc2dc3
spec:
  clusterIP: 10.96.139.186
  clusterIPs:
  - 10.96.139.186
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: inference
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
