apiVersion: batch/v1
kind: Job
metadata:
  name: finite-job
spec:
  template:
    metadata: {}
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo "job started"; sleep 5; echo "job finished"
        image: busybox:1.36
        name: finite-job
        resources: {}
      restartPolicy: Never
status: {}
