apiVersion: batch/v1
kind: Job
metadata:
  name: finite-job
spec:
  template:
    metadata: {}
    spec:
      containers:
        - name: finite-job
          image: busybox:1.36
          command:
            - sh
            - -c
            - echo "job started"; sleep 5; echo "job finished"
      restartPolicy: Never
status: {}
