apiVersion: v1
kind: Pod
metadata:
  labels:
    run: impossible-request
  name: impossible-request
spec:
  containers:
  - image: busybox:1.36
    name: impossible-request
    command:
      - sleep
      - "3600"
    resources:
      requests:
        cpu: "100"
        memory: 128Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
