FROM python:3.12-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    procps \
    iproute2 \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir torch

WORKDIR /workspace

COPY train.py /workspace/train.py

CMD ["python", "train.py"]
