FROM ubuntu:22.04

# To prevent from being asked to type Y (yes)
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -o Acquire::Retries=3 && apt-get install -y \
    --no-install-recommends \
    build-essential \
    cmake \
    git \
    curl \
    tmux \
    htop \
    sysstat \
    procps \
    strace \
    lsof \
    iproute2 \
    iputils-ping \
    psmisc \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
CMD ["/bin/bash"]
