name: Build PyTorch DDP Container

on:
  push:
    branches: ["main"]
    paths:
      - 'training/**'
      - '.github/workflows/build-training-env.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lowercase actor
        id: actor_lower
        run: |
          echo "username=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | \
          podman login ghcr.io \
          -u "${{ steps.actor_lower.outputs.username }}" \
          --password-stdin

      - name: Build and push
        run: |
          IMAGE_NAME="ghcr.io/${{ steps.actor_lower.outputs.username }}/pytorch-ddp:latest"

          podman manifest create "$IMAGE_NAME"

          podman build \
            --platform linux/amd64 \
            --file ./training/Containerfile \
            --manifest "$IMAGE_NAME" \
            ./training

          podman build \
            --platform linux/arm64 \
            --file ./training/Containerfile \
            --manifest "$IMAGE_NAME" \
            ./training

          podman manifest push --all \
            "$IMAGE_NAME" \
            "docker://$IMAGE_NAME"
