name: Build Linux Systems Lab

on:
  push:
    branches: [ "main" ]
    paths:
      - 'linux/Containerfile'
      - '.github/workflows/build-cpp-env.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 💡 깃허브 아이디를 소문자로 변환 (대소문자 꼬임으로 인한 빌드/푸시 에러 방지)
      - name: Change actor to lowercase
        id: actor_lower
        run: |
          echo "username=$(echo '${{ github.actor }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      # 멀티 아키텍처(ARM64) 에뮬레이션을 위해 QEMU 설치 스텝 추가
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to GitHub Container Registry with Podman
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u "${{ steps.actor_lower.outputs.username }}" --password-stdin

      - name: Build and push Podman image (Multi-platform)
        run: |
          IMAGE_NAME="ghcr.io/${{ steps.actor_lower.outputs.username }}/mle-cpp-env:latest"

          # 1. 멀티 아키텍처를 묶어줄 빈 매니페스트 리스트(컨테이너 주소) 생성
          podman manifest create "$IMAGE_NAME"

          # 2. 인텔/AMD(amd64)용 이미지 빌드 후 매니페스트에 추가
          podman build \
            --platform linux/amd64 \
            --security-opt seccomp=unconfined \
            --file ./linux/Containerfile \
            --manifest "$IMAGE_NAME" .

          # 3. 맥북 M시리즈(arm64)용 이미지 빌드 후 매니페스트에 추가
          podman build \
            --platform linux/arm64 \
            --security-opt seccomp=unconfined \
            --file ./linux/Containerfile \
            --manifest "$IMAGE_NAME" .

          # 4. 묶여진 매니페스트 리스트 전체를 한 번에 GitHub Packages로 푸시
          podman manifest push --all "$IMAGE_NAME" "docker://$IMAGE_NAME"
